### ISSUE TITLE
revise how third-party-licenses.md is generated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sherpa#64] opened 2016-07-13 19:41 UTC
This was encountered on 7/13/16 while publishing Function Builder 1.0.0, and discussed a bit on Skype.

The current version of the report is viewable at:
https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

According to [Sim Deployment Guidelines](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md), this file is supposed to be updated every time that a sim is publicly deployed:

> (10) The 3rd party contributions page must be updated. Directions for how to do this are in reportThirdParty.js. Brace yourself-- this will take >30 minutes since you will need to build all of the simulations in order to access their 3rd party encumbrances. After running this, the updated third-party-licenses.md file should be checked in to GitHub, which will make it publicly available to people who click on "3rd party contributions" from the sim. If this process is too cumbersome, in the future we can discuss ways to just generate a report for the new sim and integrate it into the existing report.

The instructions in [reportThirdParty.js](https://github.com/phetsims/chipper/blob/master/js/grunt/reportThirdParty.js) look complicated.

So we have a complicated, onerous process for generating this report. And as of 7/13/16, this hasn't been done for 3.5 months.

First, we should verify that the current content of the report is what is really desired. The report currently shows 3rd-party dependencies for master of all runnable, not the 3rd-party dependencies for published versions of sims.  So it includes sims that haven't yet been publish, and runnables that will never be published (e.g. demos for joist, sun, etc.)  Assuming that the current report is as desired...

Suggestion for simplifying how the report is created and maintained:

(1) Remove version numbers from the "This report is for the following simulations" section, and simply indicate that it reflects master of the listed runnables, as of a specified date.

(2) Populate the "Third-party Code" and "Third-party Code License Summary" sections directly from sherpa/lib/license.json.   There is no harm in including a 3rd-party library that is unused, and it's certainly not worth having to build all sims to include only libraries that are actually used.

(3) Populate the "Third-party Media" and "Third-party Media License Summary" sections by parsing the license.json files for all runnables. This does not require building the sims.

(4) Do this as a weekly task, immediately after running test-server. Running test-server will identify unused media files.

**Comment by pixelzoom** [comment] 2016-07-13 20:07
This report also feels like it needs a title.

**Comment by samreid** [comment] 2016-07-14 18:44
If we could download the published simulations from the website, then we could use this same script to populate this report.

@pixelzoom and @ariel-phet pointed out we should also populate the "3rd party libraries" column on the sim pages.

**Comment by samreid** [comment] 2016-07-14 18:47
I'll take a look at the idea from the preceding comment, then afterwards coordinate with @mattpen to work on adding the 3rd party libraries into the sim pages.

**Comment by samreid** [comment] 2016-07-14 18:48
We'll keep the version numbers in the report, since they will reflect the published versions.

**Comment by samreid** [comment] 2016-07-14 19:29
I parsed http://phet.colorado.edu/en/simulations/category/html and extracted the published html sim names:

acid-base-solutions
area-builder
arithmetic
balancing-act
balancing-chemical-equations
balloons-and-static-electricity
beers-law-lab
bending-light
build-an-atom
color-vision
concentration
energy-skate-park-basics
faradays-law
forces-and-motion-basics
fraction-matcher
friction
function-builder
graphing-lines
gravity-force-lab
hookes-law
isotopes-and-atomic-mass
john-travoltage
least-squares-regression
molarity
molecules-and-light
molecule-shapes
molecule-shapes-basics
neuron
ohms-law
ph-scale
ph-scale-basics
reactants-products-and-leftovers
resistance-in-a-wire
trig-tour
under-pressure
wave-on-a-string

**Comment by samreid** [comment] 2016-07-14 21:07
I've updated the script, updated the docs and added instructions at the top.  I also regenerated the new license file.  The new script takes about 10 seconds to run and reports on the published versions.  I did *not* take time to iterate through the existing code and refactor/document it, but I did add code comments for the new code.

It is in a good position now for another developer to take it for a test drive to make sure it is robust.

@pixelzoom can you take it for a test drive?  Instructions as reported at the top of reportThirdParty.js are:

 * cd chipper
 * grunt report-third-party
 * // then push the updated license file to sherpa 

You will likely not see any changes to the license file unless someone publishes a new sim between now and when you run the script.

**Comment by mattpen** [comment] 2016-07-15 16:10
@samreid - To get this data in the database, I think the easiest option would be to modify your script so that it creates a second file in json format with the 3rd party information and sends it to the website in a POST request.  This will make it easier to parse in tomcat.  Is it ok with you if I add that to the script, or should I wait until after CM reviews it?

**Comment by samreid** [comment] 2016-07-15 17:40
@mattpen that sounds like a good plan, let's wait until @pixelzoom takes a look before proceeding.

**Comment by pixelzoom** [comment] 2016-07-19 15:55
Review comments...

(1) This comment in reportThirdParty.js is a little vague and confusing:

```12   * Third party entries are parsed from HTML, see getLicenseEntry.js```

"HTML" undoubtedly means "the built HTML file for simulations", but someone who is new to this is unlikely to know that.  And getLicenseEntry.js doesn't have anything to do with HTML files, it operates on license.json files.

(2) SHERPA constants

`SHERPA` constant is defined here:

```js
22 var SHERPA = '../sherpa';
``

and should be used here:

```js
28 var _ = require( '../../../sherpa/lib/lodash-2.4.1.min' ); // eslint-disable-line require-statement-match
37 var output = '../sherpa/third-party-licenses.md';
```

(3) Vestigial test code?

I don't see any documentation that indicates how to test on a build directory. Can this be deleted?
```js
111 // shortcut to avoid looking at the -iframe.html files when testing on a build directory.
112 !ChipperStringUtils.endsWith( filename.toLowerCase(), '-iframe.html' ) ) {
```

(4) Lack of verification and error handling

This task doesn't contain a single assertion or error message, doesn't look very robust.  For example, shouldn't this `if` statement have an else clause that handles a missing HTML file?

```js
117 if ( html.indexOf( 'was not found on this server' ) < 0 || html.indexOf( 'was not found on this server' ) > 400 ) {
``` 

(5) Creates files in working copy, then doesn't delete them

Throughout the build process, we've tried to avoid creating files in the working copy, so that extraneous files don't accidentally get checked into GitHub.  This task creates chipper/downloaded-sims/, then doesn't delete when the task is completed.   Recommended to create files somewhere outside the working copy (specified via a task arg), then delete them when the task is completed (with an option to not delete, if that's really important for testing).

**Comment by pixelzoom** [comment] 2016-07-19 16:06
(6) 

Usage documentation at the top of reportThirdParty.js is:

```js
 * Usage:
 * cd chipper
 * grunt report-third-party
 * // then push the updated license file to sherpa
```

But I'm allowed to run this script from any directory that knows about the task (and it appears to succeed?)  If the task indeed must be run from chipper, then either (a) verify that pwd is chipper at the beginning of the task, (b) automatically cd to chipper at the beginning of the task, or (c) move this task to chipper/Gruntfile.js (not recommended) .  If it's not required to be in chipper/, then update the documentation (this is probably the correct option).

**Comment by pixelzoom** [comment] 2016-07-19 16:19
(7) Use more descriptive var names

Rename `output` to `outputFile` (line 37), since you also have `outputString`.

Rename `json` to `licenseJSON` (line 156).

Something more descriptive than `lines` (line 179).

You have `entries` for 3rd-party code, `mediaOutput` for 3rd-party media. Use more similar var names. Perhaps `codeOutput` to correspond to `mediaOutput`, since you have `codeLicensesUsed` and `mediaLicensesUsed`?  

(7) No license?

This seems like it should fail, rather than continue, since the absence of a license is not allowed when building a sim.  So if there's a sim published that has no license for a media file, we need to know about it.  Or at least warn the user to inspect it, rather than silently write something to the report.

```js
233      var license = compositeMedia[ mediaKey ].license.trim();
      if ( license.length === 0 ) {
        license = '(no license)';
      }
```

(8) Media exception?

I'm not sure what's going on here. Document it? If there's really a problem encountered here, should it be written to the report, or should this task fail?

```js
      if ( compositeMedia[ mediaKey ].exception ) {
        mediaEntryLines.push( 'Exception: ' + compositeMedia[ mediaKey ].exception );
      }
```

**Comment by pixelzoom** [comment] 2016-07-19 16:25
(9) Which fields are required in license.json?

Based on this chunk of code:

```js
222
     if ( copyrightStatement.length === 0 ) {
        copyrightStatement = '(no text)';
      }

      if ( projectURL.length === 0 ) {
        projectURL = '(no project url)';
      }

      var notes = compositeMedia[ mediaKey ].notes.trim();
      if ( notes.length === 0 ) {
        notes = '(no notes)';
      }

      var license = compositeMedia[ mediaKey ].license.trim();
      if ( license.length === 0 ) {
        license = '(no license)';
      }
```

It appears that all of these fields are required to be in license.json, but they may be the empty string.  Is that requirement and the list of fields (and their semantics) documented somewhere?

**Comment by pixelzoom** [comment] 2016-07-19 16:29
(10) Wrong semantics for license.json field

```js
220 var copyrightStatement = compositeMedia[ mediaKey ].text.join( '<br>' ).trim();
```

The `text` field in license.json is not a copyright statement. It does (in most cases) contain the copyright info. In other cases it contains the copyright and other info. In some cases it contains just a description.   Do we need an explicit 'copyright' field in license.json?  Or can we just rename this var so that it's not misleading?

**Comment by pixelzoom** [comment] 2016-07-19 16:30
(11) Update sherpa/README.md

... which still says:

```
For developers: when adding a new library or changing third-party-licenses.json, please update the third-party-licenses.md
file by following these steps:

1. grunt-all.sh
2. cd $ANY_SIM_DIR$
3. grunt report-third-party --active-runnables=true --input=$TEMP_DIR$ --output=$PATH_TO_SHERPA$/third-party-licenses.md
```

**Comment by pixelzoom** [comment] 2016-07-19 16:35
Review completed, back to @samreid.

**Comment by samreid** [comment] 2016-07-25 00:13
I addressed (1) - (3) in the above commits.  For (4), I added handling for the error case where the HTML files cannot be downloaded, will commit below.  And I'll create a separate issue for more general error handling.

**Comment by samreid** [comment] 2016-07-25 00:22
Addressed (5) above, files are cleaned up afterwards and before (the latter in case of interruption).

**Comment by samreid** [comment] 2016-07-25 00:23
Addressed (6) above.

**Comment by samreid** [comment] 2016-07-25 02:32
I switched to more described var names in the preceding commit.

**Comment by samreid** [comment] 2016-07-25 02:46
To address the second (7), I added an assertion that the license exists in the preceding commit and removed the substitution of (no license).

**Comment by samreid** [comment] 2016-07-25 02:50
For (8) I wrote up docs to explain the media license exceptions.

**Comment by samreid** [comment] 2016-07-25 02:53
For (9) @pixelzoom said:

> (9) Which fields are required in license.json?
> It appears that all of these fields are required to be in license.json, but they may be the empty string. Is that requirement and the list of fields (and their semantics) documented somewhere?

He continued in the next comment:
> [EDIT: Looks like the fields are documented in getLicenseEntry.js, which is probably the motivation for the comment in (1).]

Yes, indeed getLicenseEntry.js indicates the fields and which are optional.

It would be nicer to check earlier on that the contents are not the empty string, Ill create a separate issue for that.

**Comment by samreid** [comment] 2016-07-25 02:59
In the preceding commits, I renamed var copyrightStatement and updated the sherpa README.md.

I've addressed all of @pixelzoom's feedback or moved them to new issues.  @mattpen you are clear to proceed to move this data to the database as you discussed in https://github.com/phetsims/sherpa/issues/64#issuecomment-232995908

I'll create a separate issue for that.

@pixelzoom please review my changes and close this issue if everything seems OK.

**Comment by pixelzoom** [comment] 2016-07-26 20:32
Issue (4) in https://github.com/phetsims/sherpa/issues/64#issuecomment-233678870 does not appear to have been addressed. If an HTML file cannot be loaded, the task silently continues.

I realize that you are now verifying the download, i.e.:

```js
326  download( url, 'downloaded-sims/' + sim + '_en.html', function( err ) {
327    assert && assert( !err, 'Error during download: ' + err );
```

... but if you're checking for an error with:

```js
117  if ( html.indexOf( 'was not found on this server' ) < 0 || html.indexOf( 'was not found on this server' ) > 400 ) {
```

... then there should be an `else` clause that handles the case where the if expression fails.

**Comment by samreid** [comment] 2016-07-26 20:46
In the preceding commit, I added this documentation:

```js
// If you request a page that doesn't exist, Apache returns HTML that says the page "was not found on this server"
// Since we are looping through all active-sims, there are likely to be many simulations for which published
// HTML is not available.  This is not an error, it is simply how we can differentiate between active-sims and
// published sims.  
```

Should we go the extra mile and start manually maintaining lists of published sims, so that this logic wouldn't be necessary?  Or perhaps there is some website api query we can make to discover the list of published HTML5 sims?

**Comment by pixelzoom** [comment] 2016-07-26 20:51
Great, very important documentation, now I understand what's going on here.

I don't think we need to do the "extra mile" here, especially since the functionality of this task is being moved server-side, where (presumably) there's more knowledge about which sims are actually published.

All issues addressed. Closing.

**Comment by zepumph** [comment] 2020-02-06 22:52
While looking into un-issued TODOs in chipper, I found a todo added from this issue to `reportThirdParty.js`:

```

    // TODO: is this a real license?  Why is there logic here but nowhere else?  Perhaps files annotated with
    // TODO: contact phethelp@colorado.edu are leaking into the HTML files unnecessarily, see https://github.com/phetsims/sherpa/issues/64
    if ( license !== 'contact phethelp@colorado.edu' ) {
      mediaOutput.push( mediaEntryLines.join( '<br>' ) );

      if ( mediaLicensesUsed.indexOf( license ) < 0 ) {
        mediaLicensesUsed.push( license );
      }
    }
  }
```

This todo and `if` statement were added by @samreid, so assigning there under a lower priority.

**Comment by pixelzoom** [comment] 2020-02-11 21:08
The TODOs identified in the previous comment sound like a new issue.   The original problem ("complicated, onerous process for generating this report") was addressed when the responsibility for generating the report was moved to the server.

**Comment by zepumph** [comment] 2020-02-18 00:28
See https://github.com/phetsims/sherpa/issues/78.

**Comment by samreid** [comment] 2020-05-21 21:57
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by samreid** [comment] 2020-05-26 18:45
Unassigning until we work on this part again.

**Comment by samreid** [comment] 2021-02-26 13:28
There are no longer any TODOs referencing this issue, closing.

**Closed by samreid** 2021-02-26 13:28 UTC
