### ISSUE TITLE
Rename the text plugin

### ISSUE THREAD

**Issue by samreid** [phetsims/sherpa#11] opened 2014-12-01 16:36 UTC
The requirejs plugin currently does not contain version info in its name.  It should be renamed to include the version in the filename, as per our convention for our other 3rd party dependencies.  However, I noticed that many simulations are referring to sherpa/text in their config files (I see 66 occurrences across our sims).  So I thought I'd check in with other developers before making a 66-repo commit.  I already checked in text-2.0.12.js.  This change would be to update all simulations config files to point to it, then to delete sherpa/text.js.  Also, I was surprised to see so many simulations pointing to sherpa/text.js.  Is that something we have been using, or vestigial?

Please chime in @pixelzoom @jbphet @jonathanolson @aaronsamuel137, thanks!

**Comment by samreid** [comment] 2015-03-11 04:44
@ariel-phet can you assign this to someone with enough time to work on it?

**Comment by pixelzoom** [comment] 2015-05-08 19:51
Duplicate of https://github.com/phetsims/sherpa/issues/15, closing.

**Closed by pixelzoom** 2015-05-08 19:51 UTC
Labels: enhancement
